### ISSUE TITLE
Streaming video over Device Streams

### ISSUE THREAD

**Issue by ben-kotvis** [Azure-Samples/azure-iot-samples-csharp#105]
It appears that streaming video over HTTP doesn't work.  I was barely able to get a web site to display over HTTP (in other words, it doesn't work every time).  Is this supported?

This is the error I get:

Unhandled Exception:
Unhandled Exception: Microsoft.Azure.Devices.Common.Exceptions.IotHubException: {"Message":"{\"errorCode\":504101,\"trackingId\":\"cce140dd335c41fd90047208d8f7f0d0-TimeStamp:02/11/2020 01:36:39\",\"message\":\"Timed out waiting for the response from device.\",\"info\":{\"timeout\":\"00:01:00\"},\"timestampUtc\":\"2020-02-11T01:36:39.4565857Z\"}","ExceptionMessage":""}
   at Microsoft.Azure.Devices.HttpClientHelper.<ExecuteAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.HttpClientHelper.<PostAsync>d__26`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.AmqpServiceClient.<CreateStreamAsync>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at AI.Box.DeviceStreamService.StreamingService.<HandleIncomingConnectionsAndCreateStreams>d__6.MoveNext() in C:\Users\bkotvis\Source\Repos\AI-Box\ConnectedCommunities.AI.Box\AI.Box.DeviceStreamService\StreamingService.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
Microsoft.Azure.Devices.Common.Exceptions.IotHubException: {"Message":"{\"errorCode\":504101,\"trackingId\":\"d9b0ecc6d1ca4ac98d4ee8c7cfd06970-TimeStamp:02/11/2020 01:36:39\",\"message\":\"Timed out waiting for the response from device.\",\"info\":{\"timeout\":\"00:01:00\"},\"timestampUtc\":\"2020-02-11T01:36:39.1850481Z\"}","ExceptionMessage":""}
   at Microsoft.Azure.Devices.HttpClientHelper.<ExecuteAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.HttpClientHelper.<PostAsync>d__26`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.AmqpServiceClient.<CreateStreamAsync>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at AI.Box.DeviceStreamService.StreamingService.<HandleIncomingConnectionsAndCreateStreams>d__6.MoveNext() in C:\Users\bkotvis\Source\Repos\AI-Box\ConnectedCommunities.AI.Box\AI.Box.DeviceStreamService\StreamingService.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
C:\Program Files\dotnet\dotnet.exe (process 9892) exited with code 0.

**Comment by dme-development** [comment]
We are seeing the same behavior here. When trying to proxy an internal administrator interface via the browser, we can see the page (html) being loaded via device streams proxy, but resources like css & javascript fail to load as expected. This is always accompanied by errors like 504101 - Timed out waiting for the response from device.

On the device itself, there are different errors:
- The WebSocket is in an invalid state ('Aborted') for this operation. Valid states are: 'Open, CloseReceived, CloseSent'
- Got an exception: System.Net.WebSockets.WebSocketException (284143800): The server returned status code '408' when status code '101' was expected.
- Got an exception: System.Net.WebSockets.WebSocketException (2): The server returned status code '401' when status code '101' was expected.

It would be great to see a working sample for tunneling an http browser request via device streams.
