### ISSUE TITLE
Device local proxy existing will null pointer exception

### ISSUE THREAD

**Issue by rezasherafat** [Azure-Samples/azure-iot-samples-csharp#30]
Error reported on behalf of the customer (TS.) trying a VNC scenario using the proxy setup.
* Windows 10 LTSB
* Usage: TightVNC process (5901)

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Azure.Devices.Client.Transport.AmqpTransportHandler.WaitForDeviceStreamRequestAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass25_0.<<WaitForDeviceStreamRequestAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.WaitForDeviceStreamRequestAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.WaitForDeviceStreamRequestAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Samples.DeviceStreamSample.RunSampleAsync(Boolean acceptDeviceStreamingRequest) in C:\Temp\azure-iot-samples-csharp-master_stream\azure-iot-samples-csharp-master\iot-hub\Quickstarts\device-streams-proxy\device\DeviceStreamSample.cs:line 61
   at Microsoft.Azure.Devices.Client.Samples.DeviceStreamSample.RunSampleAsync() in C:\Temp\azure-iot-samples-csharp-master_stream\azure-iot-samples-csharp-master\iot-hub\Quickstarts\device-streams-proxy\device\DeviceStreamSample.cs:line 54
   at Microsoft.Azure.Devices.Client.Samples.Program.Main(String[] args) in C:\Temp\azure-iot-samples-csharp-master_stream\azure-iot-samples-csharp-master\iot-hub\Quickstarts\device-streams-proxy\device\Program.cs:line 76
```

**Comment by rezasherafat** [comment]
@ewertons as FYI

**Comment by ewertons** [comment]
There was an issue in the AmqpTransportHandler that could cause the nullreference exception, and it has been fixed by this commit https://github.com/Azure/azure-iot-sdk-csharp/pull/768/commits/40ed10839489440255ba5ab1027176bd4cc34f1f in the pending PR https://github.com/Azure/azure-iot-sdk-csharp/pull/768
As soon as the PR gets approved and merged, we will have an ETA of when the code will make into the preview branch and packages.

**Comment by ewertons** [comment]
However, it would be good to get more details from the customer to make sure they are not hitting another issue (although improbable).

- Which sample are they using?
- Could we get the exact description of the steps performed by the customer (started sample X, using protocol Y, waited N seconds, hit the issue)? 
- Would it be possible for the customer to attempt the same scenario using the actual code from https://github.com/Azure/azure-iot-sdk-csharp/tree/preview? That way we could get debug bits and more precise callstacks.
- Also there was a comment mentioning that the customer hit the same issue with other protocols. Which protocols in specific? Could we get callstacks for those too please?

**Comment by HariharanAnantharaman** [comment]
Hi,
1. We experienced the issue while running the code downloaded from the location [Here](https://docs.microsoft.com/en-us/azure/iot-hub/quickstart-device-streams-proxy-csharp)

2. This is the step I followed to replicate the issue 

           a. Start the VNC process in admin mode. Remove the security required in the VNC softwares . Verify that processes are running by cross checking the port numbers and process file in the Windows resource monitor(resmon)
           b. Navigate to the location of code. Run "dotnet build" followed by dotnet run <<device connection string>>  localhost 5900
 Waited for approximately a  minute. Than the error came up on the screen.

3. Will test using the preview branch and will update

4. Attached are the files which has stack trace for other protocols.
[stacktrace_amqp_websocket.txt](https://github.com/Azure-Samples/azure-iot-samples-csharp/files/2816817/stacktrace_amqp_websocket.txt)
[stacktract_amqp.txt](https://github.com/Azure-Samples/azure-iot-samples-csharp/files/2816818/stacktract_amqp.txt)
[stacktract_mqtt.txt](https://github.com/Azure-Samples/azure-iot-samples-csharp/files/2816819/stacktract_mqtt.txt)
[stacktract_Mqtt_WebSocket.txt](https://github.com/Azure-Samples/azure-iot-samples-csharp/files/2816820/stacktract_Mqtt_WebSocket.txt)

**Comment by rezasherafat** [comment]
@HariharanAnantharaman, the new [preview SDK release](https://www.nuget.org/packages/Microsoft.Azure.Devices.Client/1.29.0-preview-002) should address the AMQP issues you reported. PR #42 is the sample should also address the cancellation token timeout you faced using MQTT protocol.

Please try again by getting the latest sample and rebuilding the project using the latest SDK. I am also closing this issue - please reopen if there are remaining issues.
