### ISSUE TITLE
Unhandled exception using device streams sample with MQTT

### ISSUE THREAD

**Issue by rezasherafat** [Azure-Samples/azure-iot-samples-csharp#37]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ X ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> run device streaming SSH samples with MQTT protocol

### Any log messages given by the failure
```
Unhandled Exception: Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Transient network error occurred, please retry. ---> System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.SemaphoreSlim.WaitUntilCountOrTimeoutAsync(TaskNode asyncWaiter, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.WaitForDeviceStreamRequestAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass25_0.<<WaitForDeviceStreamRequestAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.WaitForDeviceStreamRequestAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.WaitForDeviceStreamRequestAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Samples.DeviceStreamSample.RunSampleAsync(Boolean acceptDeviceStreamingRequest) in C:\Techolution\IOTPractise\MicrosoftIotSuiteSolutions\DeviceStreaming\azure-iot-samples-csharp-master\azure-iot-samples-csharp-master\iot-hub\Quickstarts\device-streams-proxy\device\DeviceStreamSample.cs:line 61
   at Microsoft.Azure.Devices.Client.Samples.DeviceStreamSample.RunSampleAsync() in C:\Techolution\IOTPractise\MicrosoftIotSuiteSolutions\DeviceStreaming\azure-iot-samples-csharp-master\azure-iot-samples-csharp-master\iot-hub\Quickstarts\device-streams-proxy\device\DeviceStreamSample.cs:line 54
   at Microsoft.Azure.Devices.Client.Samples.Program.Main(String[] args) in C:\Techolution\IOTPractise\MicrosoftIotSuiteSolutions\DeviceStreaming\azure-iot-samples-csharp-master\azure-iot-samples-csharp-master\iot-hub\Quickstarts\device-streams-proxy\device\Program.cs:line 76
```

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jenoola** [comment]
could you please specify which OS you are using? I do not see this on Win 10

**Comment by jenoola** [comment]
@rezasherafat do you still see the issue? If yes, please, provide details for your environment.
