### ISSUE TITLE
Unauthorized exception in device streams echo sample with AMQP over websockets and certs auth

### ISSUE THREAD

**Issue by rezasherafat** [Azure-Samples/azure-iot-samples-csharp#39]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ X ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Code snippet below along with the streaming echo sample.

```csharp
public static class Program
    {
        public static int Main(string[] args)
        {
            var cert = new X509Certificate2(@"/home/nandan/nanca/certs/new-edge-device.cert.pfx", "1234");
            var auth = new DeviceAuthenticationWithX509Certificate("MySecStreamDev", cert);
           

            using (DeviceClient deviceClient = DeviceClient.Create("DevStreamPPIoTHub.azure-devices.net", auth, TransportType.Amqp_WebSocket_Only))
            {
                if (deviceClient == null)
                {
                    Console.WriteLine("Failed to create DeviceClient!");
                    return 1;
                }

                var sample = new DeviceStreamSample(deviceClient);
                sample.RunSampleAsync().GetAwaiter().GetResult();
            }

            Console.WriteLine("Done.\n");
      }
```

### Any log messages given by the failure
>

```
Unhandled Exception: Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException: 
Tracking Id:4ea66322278e4659b903a4c57915f7da-G:5-TimeStamp:02/07/2019 03:51:30
   at Microsoft.Azure.Devices.Client.Transport.AmqpTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass27_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass41_0.<<OpenAsyncInternal>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass23_0.<<EnableStreamsAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnableStreamsAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.EnableStreamAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.WaitForDeviceStreamRequestAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Samples.DeviceStreamSample.RunSampleAsync(Boolean acceptDeviceStreamingRequest) in /home/nandan/sdkcsharp/azure-iot-samples-csharp-master/iot-hub/Quickstarts/device-streams-echo/device/DeviceStreamSample.cs:line 33
   at Microsoft.Azure.Devices.Client.Samples.DeviceStreamSample.RunSampleAsync() in /home/nandan/sdkcsharp/azure-iot-samples-csharp-master/iot-hub/Quickstarts/device-streams-echo/device/DeviceStreamSample.cs:line 24
   at Microsoft.Azure.Devices.Client.Samples.Program.Main(String[] args) in /home/nandan/sdkcsharp/azure-iot-samples-csharp-master/iot-hub/Quickstarts/device-streams-echo/device/Program.cs:line 42
```

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by rezasherafat** [comment]
The latest [preview SDK nuge release](https://www.nuget.org/packages/Microsoft.Azure.Devices.Client/1.29.0-preview-002) should fix this issue.
