### ISSUE TITLE
Device streams ServiceClient webproxy problem

### ISSUE THREAD

**Issue by HiroyukiSakoh** [Azure-Samples/azure-iot-samples-csharp#41]
### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> [here](https://github.com/HiroyukiSakoh/DeviceStream/commit/4931bd79451301ecc278e9de81e42a27beee32b9#diff-0ded5535d969883458f6cdca81035ccf) 

### Any log messages given by the failure
> Some connections are not via webproxy.
> Depending on the network configuration, an error occurs in the connection.

### Expected/desired behavior
> All connections(Http/WebSocket) are via webproxy.

### OS and Version?
> Windows 10

### Versions
> Microsoft.Azure.Devices 1.27.0-preview-002

### Mention any other details that might be useful

Hi,
I'm trying a device stream proxy with a quick start program.

If both the device client and the service client are inside webproxy,
I was checking how it would work.

I set up a webproxy for the service client,
A connection error occurred at Microsoft.Azure.Devices.ServiceClient.CreateStreamAsync.

After setting webproxy to `httpClientObjWithPerRequestTimeout` of `Microsoft.Azure.Devices.HttpClientHelper` using reflection,
It worked correctly.
https://github.com/HiroyukiSakoh/DeviceStream/blob/7de77c0ba6b8e48000eb108e59285e65dbfbab83/device-streams-proxy/service/Program.cs#L80-L89

In `Microsoft.Azure.Devices.HttpClientHelper`,
Webproxy is set to `httpClientObj`, but it is not set to `httpClientObjWithPerRequestTimeout`.
Is that's bug?
https://github.com/Azure/azure-iot-sdk-csharp/blob/7f37ee1b4526bd6bcaf3b887b6ed7048777c10b4/common/src/service/HttpClientHelper.cs#L52-L73

----
### Minimal steps to reproduce
> [here](https://github.com/HiroyukiSakoh/DeviceStream/commit/4931bd79451301ecc278e9de81e42a27beee32b9) and [here](https://github.com/HiroyukiSakoh/DeviceStream/commit/83f456fd5a0d0698d4bc7bfb6f4e6d25a7d95abc)

**Comment by jenoola** [comment]
@HiroyukiSakoh could you please clarify what exactly are you trying to achieve? Do you want your device/service client connect to network via proxy and stream them or do you want to use device streaming to turn your device/service clients into proxies?

**Comment by HiroyukiSakoh** [comment]
@jenoola 
I want device/service client connect to network via webproxy.

![image](https://user-images.githubusercontent.com/38931510/55842979-c882f080-5b70-11e9-8c39-fb4159443a5a.png)

**Comment by jenoola** [comment]
I see. Let me investigate and I'll get back to you when I have an update

**Comment by jenoola** [comment]
@HiroyukiSakoh sorry for the late update. I don't really see issues with the sample in my setup. I use Microsoft.Azure.Devices 1.29.0-preview-002, and I have Ubuntu VM instead of RaspPi. Also, I've noticed that in my environment Fiddler has to use another port because 8888 is used by another process. I didn't make any changes in the code of the sample. Could you answer a couple of questions?
1. What region is your IoTHub located at? DeviceStreaming is available only for Central US and Central US EUAP.
2. What OS are you using on your RaspPi?

**Comment by HiroyukiSakoh** [comment]
@jenoola 
1. Central US
1. I use Raspbian   stretch, but this is not a problem on the device side.
  The problem occurs even if the   connection destination is SSH, TDS (SQL Server), or HTTP.
1. Operation differs depending on whether you can directly access the Internet from the environment where the service proxy is running.
  * Pattern 1: An exception occurs when executed in an environment where direct access to the Internet is not possible (DNS reference is not possible)
```
Microsoft.Azure.Devices.Common.Exceptions.IotHubCommunicationException
--
HResult=0x80131500
Message=No such host is known
Source=Microsoft.Azure.Devices
Stack trace:
at   Microsoft.Azure.Devices.HttpClientHelper.<ExecuteAsync>d__35.MoveNext()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task   task)
at   Microsoft.Azure.Devices.HttpClientHelper.<PostAsync>d__26`2.MoveNext()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task   task)
at   Microsoft.Azure.Devices.AmqpServiceClient.<CreateStreamAsync>d__47.MoveNext()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task   task)
at   System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
at   Microsoft.Azure.Devices.Samples.DeviceStreamSample.<HandleIncomingConnectionsAndCreateStreams>d__6.MoveNext()   in   C:\Users\hsako3\Desktop\DeviceStream-master\device-streams-proxy\service\DeviceStreamSample.cs:line   70
HttpRequestException: No such host is   known.
at Microsoft.Azure.Devices.HttpClientHelper.ExecuteAsync(HttpClient   httpClient, HttpMethod httpMethod, Uri requestUri, Func`3   modifyRequestMessageAsync, Func`2 isMappedToException, Func`3   processResponseMessageAsync, IDictionary`2 errorMappingOverrides,   CancellationToken cancellationToken)
at Microsoft.Azure.Devices.HttpClientHelper.PostAsync[T,T2](Uri   requestUri, T entity, TimeSpan operationTimeout, IDictionary`2   errorMappingOverrides, IDictionary`2 customHeaders, CancellationToken   cancellationToken)
at Microsoft.Azure.Devices.AmqpServiceClient.CreateStreamAsync(Uri   uri, DeviceStreamRequest deviceStreamRequest, CancellationToken   cancellationToken)
at   Microsoft.Azure.Devices.Samples.DeviceStreamSample.HandleIncomingConnectionsAndCreateStreams(String   deviceId, ServiceClient serviceClient, TcpClient tcpClient) in   C:\Users\hsako3\Desktop\DeviceStream-master\device-streams-proxy\service\DeviceStreamSample.cs:line   70
SocketException: No such host is known.
```
  * Pattern 2: When executed in an environment with direct access to the Internet is possible
  At first glance it   seems to work correctly but some requests are directly connected to IoTub   without going through WebProxy.
  Check the communication destination of   the service proxy with netstat, Resource Monitor (resmon) or TCPView.
![image](https://user-images.githubusercontent.com/38931510/57767052-7458c680-7743-11e9-8b6c-0a2b0d80a1c3.png)

  * With [this fix](https://github.com/HiroyukiSakoh/DeviceStream/blob/7de77c0ba6b8e48000eb108e59285e65dbfbab83/device-streams-proxy/service/Program.cs#L80-L89), all requests go through WebProxy.
![image](https://user-images.githubusercontent.com/38931510/57767171-b7b33500-7743-11e9-8354-1b7eef3ac85f.png)


I created [a program](https://gist.github.com/HiroyukiSakoh/dd8770ce915e001aa33d063a51e0f691) that reproduces the same root cause problem.
The second request does not via WebProxy.

**Comment by jenoola** [comment]
For pattern 1, if it is just about host name resolution, you can set a local DNS record for your hub or add a DNS server to connection configuration, that should help. It is not SDK issue.

For pattern 2, let me look into this again.

**Comment by HiroyukiSakoh** [comment]
I suppose both patterns are the same SDK issue.
When configuring a WebProxy, hostname resolution should be done by the WebProxy, not the ServiceClient.

**Comment by HiroyukiSakoh** [comment]
https://github.com/Azure/azure-iot-sdk-csharp/pull/1178
