### ISSUE TITLE
Device Streaming Errror - Forbidden Access Permissions

### ISSUE THREAD

**Issue by terrymandin** [Azure-Samples/azure-iot-samples-csharp#65]
### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
1. Clone: https://github.com/Azure-Samples/azure-iot-samples-csharp
2. Change directory to 
```
azure-iot-samples-csharp\iot-hub\Quickstarts\device-streams-proxy\service
```
3. Start the service
```
dotnet run HostName=<hubname>.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=<key> <deviceid> 2222
```
```
Unhandled Exception: System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at System.Net.Sockets.TcpListener.Start(Int32 backlog)
   at System.Net.Sockets.TcpListener.Start()
   at Microsoft.Azure.Devices.Samples.DeviceStreamSample.<RunSampleAsync>d__7.MoveNext() in C:\Git\azure-iot-samples-csharp\iot-hub\Quickstarts\device-streams-proxy\service\DeviceStreamSample.cs:line 92
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Samples.Program.Main(String[] args) in C:\Git\azure-iot-samples-csharp\iot-hub\Quickstarts\device-streams-proxy\service\Program.cs:line 66
```

### Expected/desired behavior
Service starts

### OS and Version?
Windows 10

### Versions
Version 1903 (OS Build 18362.175

### Mention any other details that might be useful
This may be due to a Windows 10 update I did this morning.  It was working last Friday.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by terrymandin** [comment]
The issue has somehow resolved itself.  I can no longer duplicate.
