### ISSUE TITLE
OpenSslCryptographicException exception in device-streams-proxy sample

### ISSUE THREAD

**Issue by kiranpradeep** [Azure-Samples/azure-iot-samples-csharp#73]
### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```
There are similar issues raised in Feb/2019. But I could not find an exact match.

### Minimal steps to reproduce
I followed SSH/RDP using streams quickstart documentation at microsoft docs[[1]( https://docs.microsoft.com/en-us/azure/iot-hub/quickstart-device-streams-proxy-csharp)]

### Any log messages given by the failure
An exception is thrown from: _DeviceClient::WaitForDeviceStreamRequestAsync_ method.

> xxxxxxxxxx@xxxxxxxx:~/azure-iot-samples-csharp-master/iot-hub/Quickstarts/device-streams-proxy/device$ dotnet run "HostName=xxxxxxxxx.azure-devices.net;DeviceId=xxxxxxx;SharedAccessKey=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" localhost 22
> Got an exception: System.AggregateException: One or more errors occurred. (error:2006D080:BIO routines:BIO_new_file:no such file) ---> Interop+Crypto+OpenSslCryptographicException: error:2006D080:BIO routines:BIO_new_file:no such file
>    at Interop.Crypto.CheckValidOpenSslHandle(SafeHandle handle)
>    at Internal.Cryptography.Pal.StorePal.LoadMachineStores()
>    at Internal.Cryptography.Pal.StorePal.FromSystemStore(String storeName, StoreLocation storeLocation, OpenFlags openFlags)
>    at System.Security.Cryptography.X509Certificates.X509Store.Open(OpenFlags flags)
>    at Internal.Cryptography.Pal.OpenSslX509ChainProcessor.FindCandidates(X509Certificate2 leaf, X509Certificate2Collection extraStore, HashSet`1 downloaded, HashSet`1 systemTrusted, TimeSpan& remainingDownloadTime)
>    at Internal.Cryptography.Pal.ChainPal.BuildChain(Boolean useMachineContext, ICertificatePal cert, X509Certificate2Collection extraStore, OidCollection applicationPolicy, OidCollection certificatePolicy, X509RevocationMode revocationMode, X509RevocationFlag revocationFlag, DateTime verificationTime, TimeSpan timeout)
>    at System.Security.Cryptography.X509Certificates.X509Chain.Build(X509Certificate2 certificate, Boolean throwOnException)
>    at System.Security.Cryptography.X509Certificates.X509Chain.Build(X509Certificate2 certificate)
>    at System.Net.Security.CertificateValidation.BuildChainAndVerifyProperties(X509Chain chain, X509Certificate2 remoteCertificate, Boolean checkCertName, String hostName)
>    at System.Net.Security.SecureChannel.VerifyRemoteCertificate(RemoteCertValidationCallback remoteCertValidationCallback, ProtocolToken& alertToken)
>    at System.Net.Security.SslState.CompleteHandshake(ProtocolToken& alertToken)
>    at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Net.Security.SslState.ThrowIfExceptional()
>    at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
>    at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
>    at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
>    at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__46_2(IAsyncResult iar)
>    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
>    --- End of inner exception stack trace ---
>    at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsyncInternal(CancellationToken cancellationToken)
>    at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsync(CancellationToken cancellationToken)
>    at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
>    at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass27_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
>    at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass41_0.<<OpenAsyncInternal>b__0>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(CancellationToken cancellationToken)
>    at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass23_0.<<EnableStreamsAsync>b__0>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnableStreamsAsync(CancellationToken cancellationToken)
>    at Microsoft.Azure.Devices.Client.InternalClient.EnableStreamAsync(CancellationToken cancellationToken)
>    at Microsoft.Azure.Devices.Client.InternalClient.WaitForDeviceStreamRequestAsync(CancellationToken cancellationToken)
>    at Microsoft.Azure.Devices.Client.Samples.DeviceStreamSample.RunSampleAsync(Boolean acceptDeviceStreamingRequest, CancellationTokenSource cancellationTokenSource) in /home/roots/src/try/azure-iot-samples-csharp-master/iot-hub/Quickstarts/device-streams-proxy/device/DeviceStreamSample.cs:line 70
>    at Microsoft.Azure.Devices.Client.Samples.DeviceStreamSample.RunSampleAsync(CancellationTokenSource cancellationTokenSource) in /home/roots/src/try/azure-iot-samples-csharp-master/iot-hub/Quickstarts/device-streams-proxy/device/DeviceStreamSample.cs:line 58
>    at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter.WriteMessageAsync(IChannelHandlerContext context, Object message, Func`3 exceptionHandler)
> ---> (Inner Exception #0) Interop+Crypto+OpenSslCryptographicException: error:2006D080:BIO routines:BIO_new_file:no such file
>    at Interop.Crypto.CheckValidOpenSslHandle(SafeHandle handle)
>    at Internal.Cryptography.Pal.StorePal.LoadMachineStores()
>    at Internal.Cryptography.Pal.StorePal.FromSystemStore(String storeName, StoreLocation storeLocation, OpenFlags openFlags)
>    at System.Security.Cryptography.X509Certificates.X509Store.Open(OpenFlags flags)
>    at Internal.Cryptography.Pal.OpenSslX509ChainProcessor.FindCandidates(X509Certificate2 leaf, X509Certificate2Collection extraStore, HashSet`1 downloaded, HashSet`1 systemTrusted, TimeSpan& remainingDownloadTime)
>    at Internal.Cryptography.Pal.ChainPal.BuildChain(Boolean useMachineContext, ICertificatePal cert, X509Certificate2Collection extraStore, OidCollection applicationPolicy, OidCollection certificatePolicy, X509RevocationMode revocationMode, X509RevocationFlag revocationFlag, DateTime verificationTime, TimeSpan timeout)
>    at System.Security.Cryptography.X509Certificates.X509Chain.Build(X509Certificate2 certificate, Boolean throwOnException)
>    at System.Security.Cryptography.X509Certificates.X509Chain.Build(X509Certificate2 certificate)
>    at System.Net.Security.CertificateValidation.BuildChainAndVerifyProperties(X509Chain chain, X509Certificate2 remoteCertificate, Boolean checkCertName, String hostName)
>    at System.Net.Security.SecureChannel.VerifyRemoteCertificate(RemoteCertValidationCallback remoteCertValidationCallback, ProtocolToken& alertToken)
>    at System.Net.Security.SslState.CompleteHandshake(ProtocolToken& alertToken)
>    at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Net.Security.SslState.ThrowIfExceptional()
>    at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
>    at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
>    at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
>    at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__46_2(IAsyncResult iar)
>    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)<---
> 
> Waiting again...
> 

### Expected/desired behavior
It should wait for a stream request from service side

### OS and Version?
Ubuntu 18.04 LTS

### Versions
dotnet core - 2.2.100
OpenSSL - OpenSSL 1.1.0g  2 Nov 2017

### Mention any other details that might be useful

-  An F1 tier IoTHub was created in Central US region.
- I used openssl s_client to verify if my machine had appropriate root certificates installed. _openssl s_client -connect centralus002.centralus-001.streams.azure-devices.net:443_ was successful with return code 0.
- _openssl s_client -connect xxxxxxxxxx.azure-devices.net:5671_ was also successful.
-  This error is quickly and consistently reproducible. On running the sample on an Ubuntu 18.04 LTS and I feel you will hit this error.

**Comment by kiranpradeep** [comment]
The above bug report was specific to an Ubuntu machine. I was able to get the sample working on other Ubuntu machines. But the exception message thrown, doesn't give any clue to the lib user to find the root cause. Closing.
